import { ChevronLeft } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Transaction, formatMoney } from '../../store';
import { palette, sharedStyles } from '../../theme';

type Props = { transactions: Transaction[]; onBack: () => void };
export function InsightsScreen({ transactions, onBack }: Props) { const [mode, setMode] = useState<'expense' | 'income'>('expense'); const entries = transactions.filter(item => item.type === mode); const totals = entries.reduce<Record<string, number>>((result, item) => { result[item.category] = (result[item.category] ?? 0) + Math.abs(item.amount); return result; }, {}); const rows = Object.entries(totals).sort(([, a], [, b]) => b - a); const total = rows.reduce((sum, [, amount]) => sum + amount, 0); const max = rows[0]?.[1] ?? 1; return <ScrollView contentContainerStyle={sharedStyles.page}><Pressable style={styles.back} onPress={onBack}><ChevronLeft size={18} color={palette.ink} /><Text style={styles.backText}>Settings</Text></Pressable><Text style={sharedStyles.pageTitle}>Insights</Text><Text style={sharedStyles.pageSubtitle}>Understand where your money moves</Text><View style={styles.toggle}>{(['expense', 'income'] as const).map(item => <Pressable key={item} onPress={() => setMode(item)} style={[styles.option, mode === item && styles.active]}><Text style={[styles.toggleText, mode === item && styles.activeText]}>{item === 'expense' ? 'Expenses' : 'Income'}</Text></Pressable>)}</View><View style={styles.total}><Text style={styles.label}>{mode === 'expense' ? 'TOTAL EXPENSES' : 'TOTAL INCOME'}</Text><Text style={styles.amount}>{formatMoney(total)}</Text><Text style={styles.caption}>{entries.length} transaction{entries.length === 1 ? '' : 's'} · All time</Text></View><Text style={styles.label}>BY CATEGORY</Text>{rows.length ? <View style={styles.panel}>{rows.map(([category, value]) => <View key={category} style={styles.row}><View style={styles.rowTop}><Text style={styles.category}>{category}</Text><Text style={styles.value}>{formatMoney(value)}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${Math.max((value / max) * 100, 5)}%`, backgroundColor: mode === 'expense' ? palette.coral : palette.green }]} /></View></View>)}</View> : <View style={styles.empty}><Text style={styles.category}>No {mode} categories yet</Text><Text style={styles.caption}>Add a {mode} transaction to see it here.</Text></View>}</ScrollView>; }
const styles = StyleSheet.create({ back: { flexDirection: 'row', alignItems: 'center', gap: 3, marginBottom: 16 }, backText: { color: palette.ink, fontSize: 13, fontWeight: '600' }, toggle: { flexDirection: 'row', backgroundColor: '#E8EDE8', borderRadius: 13, padding: 4, marginBottom: 14 }, option: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: 10 }, active: { backgroundColor: 'white' }, toggleText: { color: palette.muted, fontWeight: '600', fontSize: 13 }, activeText: { color: palette.ink }, total: { backgroundColor: palette.mint, borderRadius: 18, padding: 18, marginBottom: 22 }, label: { color: palette.muted, fontSize: 10, letterSpacing: 1.2, fontWeight: '700', marginBottom: 9 }, amount: { color: palette.navy, fontSize: 26, fontWeight: '700' }, caption: { color: palette.muted, fontSize: 11, marginTop: 4 }, panel: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 15 }, row: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F0F3F0' }, rowTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 9 }, category: { color: palette.ink, fontSize: 13, fontWeight: '700' }, value: { color: palette.ink, fontSize: 13, fontWeight: '700' }, track: { height: 8, borderRadius: 4, backgroundColor: '#EFF2EF', overflow: 'hidden' }, fill: { height: 8, borderRadius: 4 }, empty: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 24, alignItems: 'center' } });
