import { ArrowDownLeft, ArrowUpRight, Banknote, CreditCard, Landmark, MoreHorizontal, Plus } from 'lucide-react-native';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Account, formatMoney, Store, Transaction } from '../../store';
import { palette, sharedStyles } from '../../theme';
import { TransactionRow } from '../../components/TransactionRow';

type Props = { store: Store; onAddAccount: () => void; onAccounts: () => void; onTransactions: () => void; onTransaction: (transaction: Transaction) => void };

export function DashboardScreen({ store, onAddAccount, onAccounts, onTransactions, onTransaction }: Props) { const total = store.accounts.reduce((sum, item) => sum + item.balance, 0); const income = store.transactions.filter(item => item.type === 'income').reduce((sum, item) => sum + item.amount, 0); const expenses = Math.abs(store.transactions.filter(item => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0)); return <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><View style={styles.balanceCard}><View style={styles.header}><Text style={styles.kicker}>TOTAL BALANCE</Text><MoreHorizontal color="white" size={22} /></View><Text style={styles.balance}>{formatMoney(total)}</Text><Text style={styles.caption}>Across {store.accounts.length} accounts</Text></View><View style={styles.stats}><Stat label="Income" value={income} icon={<ArrowDownLeft color={palette.green} size={16} />} /><Stat label="Spending" value={expenses} icon={<ArrowUpRight color={palette.coral} size={16} />} /></View><Section title="Your accounts" onPress={onAccounts} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.accountRow}>{store.accounts.map(account => <AccountCard key={account.id} account={account} />)}<Pressable style={styles.addCard} onPress={onAddAccount}><Plus color={palette.green} size={20} /><Text style={styles.addText}>Add account</Text></Pressable></ScrollView><Section title="Recent activity" onPress={onTransactions} /><View style={styles.list}>{store.transactions.slice(0, 4).map(item => <TransactionRow key={item.id} transaction={item} onPress={() => onTransaction(item)} />)}</View></ScrollView>; }
function Section({ title, onPress }: { title: string; onPress: () => void }) { return <View style={sharedStyles.sectionHeader}><Text style={sharedStyles.sectionTitle}>{title}</Text><Pressable onPress={onPress}><Text style={sharedStyles.link}>See all</Text></Pressable></View>; }
function Stat({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <View style={styles.stat}><View style={styles.statTop}><Text style={styles.statLabel}>{label}</Text><View style={styles.statIcon}>{icon}</View></View><Text style={styles.statValue}>{formatMoney(value)}</Text><Text style={styles.statCaption}>This month</Text></View>; }
function AccountCard({ account }: { account: Account }) { return <View style={[styles.accountCard, { backgroundColor: account.color }]}><View style={styles.header}>{account.type === 'cash' ? <Banknote color="white" size={19} /> : account.type === 'bank' ? <Landmark color="white" size={19} /> : <CreditCard color="white" size={19} />}<MoreHorizontal color="rgba(255,255,255,.7)" size={19} /></View><Text style={styles.accountName}>{account.name}</Text><Text style={styles.accountBalance}>{formatMoney(account.balance)}</Text>{account.last4 && <Text style={styles.last4}>•••• {account.last4}</Text>}</View>; }
const styles = StyleSheet.create({ scroll: { paddingHorizontal: 22, paddingBottom: 115 }, balanceCard: { backgroundColor: palette.navy, borderRadius: 22, padding: 22, marginBottom: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between' }, kicker: { color: 'rgba(255,255,255,.62)', fontSize: 10, letterSpacing: 1.5, fontWeight: '700' }, balance: { color: 'white', fontSize: 34, fontWeight: '700', marginTop: 10 }, caption: { color: 'rgba(255,255,255,.55)', fontSize: 11, marginTop: 18 }, stats: { flexDirection: 'row', gap: 12, marginBottom: 24 }, stat: { flex: 1, backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 16, padding: 15 }, statTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, statLabel: { color: palette.muted, fontSize: 11, fontWeight: '700' }, statIcon: { width: 27, height: 27, borderRadius: 14, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center' }, statValue: { color: palette.ink, fontSize: 19, fontWeight: '700', marginTop: 12 }, statCaption: { color: palette.muted, fontSize: 11, marginTop: 3 }, accountRow: { gap: 10, paddingBottom: 25 }, accountCard: { width: 162, height: 143, borderRadius: 18, padding: 15 }, accountName: { color: 'rgba(255,255,255,.75)', fontSize: 12, marginTop: 20 }, accountBalance: { color: 'white', fontSize: 18, fontWeight: '700', marginTop: 4 }, last4: { color: 'rgba(255,255,255,.6)', fontSize: 11, marginTop: 8, letterSpacing: 1 }, addCard: { width: 130, height: 143, borderRadius: 18, borderWidth: 1.5, borderColor: '#BBDAC6', borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', gap: 8 }, addText: { color: palette.green, fontSize: 12, fontWeight: '700' }, list: { backgroundColor: 'white', borderRadius: 18, paddingHorizontal: 15, borderWidth: 1, borderColor: palette.line } });
