import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, StatusBar, StyleSheet, Text, View } from 'react-native';
import { Account, Category, loadStore, palette, Profile, saveStore, Store, Transaction } from '../store';
import { BottomNav, AppTab } from '../components/BottomNav';
import { DashboardScreen } from '../features/dashboard/DashboardScreen';
import { ActivityScreen } from '../features/activity/ActivityScreen';
import { InsightsScreen } from '../features/insights/InsightsScreen';
import { AccountsScreen } from '../features/accounts/AccountsScreen';
import { AccountEditor } from '../features/accounts/AccountEditor';
import { SettingsScreen, CategoriesScreen } from '../features/settings/SettingsScreen';
import { CategoryEditor } from '../features/settings/CategoryEditor';
import { AddTransactionModal } from '../features/transactions/AddTransactionModal';
import { TransactionDetails, TransactionEditor } from '../features/transactions/TransactionModals';

export function TrackItApp() {
  const [store, setStore] = useState<Store>({ accounts: [], transactions: [], categories: [], profile: { name: '', email: '' } });
  const [tab, setTab] = useState<AppTab>('home');
  const [accountModal, setAccountModal] = useState(false);
  const [editingAccount, setEditingAccount] = useState<Account>();
  const [categoryModal, setCategoryModal] = useState(false);
  const [editingCategory, setEditingCategory] = useState<Category>();
  const [addTransaction, setAddTransaction] = useState(false);
  const [selectedTransaction, setSelectedTransaction] = useState<Transaction>();
  const [editingTransaction, setEditingTransaction] = useState<Transaction>();
  useEffect(() => { loadStore().then(setStore); }, []);
  useEffect(() => { if (store.accounts.length) saveStore(store); }, [store]);
  const openNewAccount = () => { setEditingAccount(undefined); setAccountModal(true); };
  const saveAccount = (account: Omit<Account, 'id'>, id?: string) => { setStore(current => ({ ...current, accounts: id ? current.accounts.map(item => item.id === id ? { ...item, ...account } : item) : [...current.accounts, { ...account, id: Date.now().toString() }] })); setAccountModal(false); };
  const deleteAccount = (id: string) => setStore(current => ({ ...current, accounts: current.accounts.filter(item => item.id !== id) }));
  const saveCategory = (category: Omit<Category, 'id'>, id?: string) => { setStore(current => ({ ...current, categories: id ? current.categories.map(item => item.id === id ? { ...item, ...category } : item) : [...current.categories, { ...category, id: Date.now().toString() }] })); setCategoryModal(false); };
  const createTransaction = (title: string, amount: number, type: 'expense' | 'income', accountId: string, categoryId: string) => { setStore(current => { const account = current.accounts.find(item => item.id === accountId) ?? current.accounts[0]; const category = current.categories.find(item => item.id === categoryId); const signed = type === 'expense' ? -amount : amount; return { ...current, accounts: current.accounts.map(item => item.id === account.id ? { ...item, balance: item.balance + signed } : item), transactions: [{ id: Date.now().toString(), title, category: category?.name ?? 'General', categoryId, amount: signed, type, date: 'Just now', account: account.name, accountId: account.id, icon: category?.icon ?? 'home' }, ...current.transactions] }; }); setAddTransaction(false); };
  const deleteTransaction = (item: Transaction) => { setStore(current => ({ ...current, accounts: current.accounts.map(account => account.id === item.accountId ? { ...account, balance: account.balance - item.amount } : account), transactions: current.transactions.filter(transaction => transaction.id !== item.id) })); setSelectedTransaction(undefined); };
  const updateTransaction = (item: Transaction, title: string, amount: number, type: 'expense' | 'income', accountId: string, categoryId: string) => { setStore(current => { const next = current.accounts.find(account => account.id === accountId) ?? current.accounts[0]; const oldId = item.accountId ?? current.accounts.find(account => account.name === item.account)?.id; const category = current.categories.find(entry => entry.id === categoryId); const signed = type === 'expense' ? -amount : amount; const accounts = current.accounts.map(account => account.id === oldId ? { ...account, balance: account.balance - item.amount + (account.id === next.id ? signed : 0) } : account.id === next.id ? { ...account, balance: account.balance + signed } : account); return { ...current, accounts, transactions: current.transactions.map(entry => entry.id === item.id ? { ...item, title, amount: signed, type, category: category?.name ?? 'General', categoryId, account: next.name, accountId: next.id, icon: category?.icon ?? 'home' } : entry) }; }); setEditingTransaction(undefined); setSelectedTransaction(undefined); };
  const name = store.profile.name.split(' ')[0] || 'there';
  return <SafeAreaView style={styles.safe}><StatusBar barStyle="dark-content" /><View style={styles.app}><View style={styles.topbar}><Text style={styles.eyebrow}>TRACKIT</Text><Text style={styles.greeting}>Good morning, {name}</Text></View>{tab === 'home' && <DashboardScreen store={store} onAddAccount={openNewAccount} onAccounts={() => setTab('accounts')} onTransactions={() => setTab('activity')} onTransaction={setSelectedTransaction} />}{tab === 'activity' && <ActivityScreen transactions={store.transactions} onTransaction={setSelectedTransaction} />}{tab === 'insights' && <InsightsScreen transactions={store.transactions} onBack={() => setTab('settings')} />}{tab === 'accounts' && <AccountsScreen accounts={store.accounts} onAdd={openNewAccount} onEdit={account => { setEditingAccount(account); setAccountModal(true); }} onDelete={id => Alert.alert('Delete account?', 'This account will be removed.', [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => deleteAccount(id) }])} />}{tab === 'settings' && <SettingsScreen profile={store.profile} categories={store.categories} onProfileChange={(profile: Profile) => setStore(current => ({ ...current, profile }))} onCategories={() => setTab('categories')} onInsights={() => setTab('insights')} />}{tab === 'categories' && <CategoriesScreen categories={store.categories} onChange={categories => setStore(current => ({ ...current, categories }))} onBack={() => setTab('settings')} onEdit={category => { setEditingCategory(category); setCategoryModal(true); }} />}<BottomNav activeTab={tab} onChange={setTab} /><Pressable style={styles.fab} onPress={() => setAddTransaction(true)}><Text style={styles.fabText}>+</Text></Pressable></View><AccountEditor visible={accountModal} account={editingAccount} onClose={() => setAccountModal(false)} onSave={saveAccount} /><CategoryEditor visible={categoryModal} category={editingCategory} onClose={() => setCategoryModal(false)} onSave={saveCategory} /><AddTransactionModal visible={addTransaction} accounts={store.accounts} categories={store.categories} onClose={() => setAddTransaction(false)} onSave={createTransaction} /><TransactionDetails transaction={selectedTransaction} onClose={() => setSelectedTransaction(undefined)} onEdit={() => { setEditingTransaction(selectedTransaction); setSelectedTransaction(undefined); }} onDelete={item => Alert.alert('Delete transaction?', 'The account balance will be restored.', [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => deleteTransaction(item) }])} /><TransactionEditor visible={Boolean(editingTransaction)} transaction={editingTransaction} accounts={store.accounts} categories={store.categories} onClose={() => setEditingTransaction(undefined)} onSave={updateTransaction} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: palette.paper }, app: { flex: 1 }, topbar: { paddingHorizontal: 22, paddingTop: 13, paddingBottom: 18 }, eyebrow: { fontSize: 10, letterSpacing: 1.4, color: palette.muted, fontWeight: '700' }, greeting: { fontSize: 22, color: palette.ink, fontWeight: '700', marginTop: 4 }, fab: { position: 'absolute', right: 22, bottom: 95, width: 54, height: 54, borderRadius: 27, backgroundColor: palette.green, alignItems: 'center', justifyContent: 'center', elevation: 5 }, fabText: { color: 'white', fontSize: 28, lineHeight: 30 } });
