import { StyleSheet } from 'react-native';
import { palette } from './store';

export const settingsStyles = StyleSheet.create({
  categoryOptions: { gap: 8, paddingBottom: 3 },
  categoryOption: { borderWidth: 1, borderColor: palette.line, borderRadius: 18, paddingHorizontal: 13, paddingVertical: 8, backgroundColor: 'white' },
  categoryOptionActive: { backgroundColor: palette.ink, borderColor: palette.ink },
  categoryOptionText: { color: palette.muted, fontSize: 12, fontWeight: '600' },
  categoryOptionTextActive: { color: 'white' },
  profileHeader: { flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: palette.navy, borderRadius: 18, padding: 18, marginBottom: 22 },
  avatar: { width: 52, height: 52, borderRadius: 26, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: palette.navy, fontSize: 23, fontWeight: '700' },
  profileName: { color: 'white', fontSize: 17, fontWeight: '700' },
  profileEmail: { color: 'rgba(255,255,255,.65)', fontSize: 12, marginTop: 4 },
  sectionLabel: { color: palette.muted, fontSize: 10, letterSpacing: 1.3, fontWeight: '700', marginBottom: 9, marginTop: 5 },
  profilePanel: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 15, marginBottom: 22 },
  menuButton: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 11 },
  menuIcon: { width: 39, height: 39, borderRadius: 12, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center' },
  menuIconText: { color: palette.green, fontSize: 20, fontWeight: '700' },
  menuTitle: { color: palette.ink, fontSize: 14, fontWeight: '700' },
  backButton: { flexDirection: 'row', alignItems: 'center', gap: 3, marginBottom: 16, paddingVertical: 4 },
  backText: { color: palette.ink, fontSize: 13, fontWeight: '600' },
  panel: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 15 },
  panelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 7 },
  panelCopy: { color: palette.muted, fontSize: 12, marginTop: 4 },
  categoryRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#F0F3F0', gap: 10 },
  categoryIcon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  categoryName: { flex: 1, color: palette.ink, fontSize: 13, fontWeight: '700' },
  categoryAction: { width: 32, height: 32, borderRadius: 10, backgroundColor: '#F0F4EF', alignItems: 'center', justifyContent: 'center' },
  preference: { marginTop: 14, backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 10 },
  colorRow: { flexDirection: 'row', gap: 13, paddingVertical: 5 },
  colorChoice: { width: 31, height: 31, borderRadius: 16 },
  colorChoiceActive: { borderWidth: 3, borderColor: palette.ink },
  analyticsToggle: { flexDirection: 'row', backgroundColor: '#E8EDE8', borderRadius: 13, padding: 4, marginBottom: 14 },
  analyticsOption: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: 10 },
  analyticsOptionActive: { backgroundColor: 'white' },
  analyticsText: { color: palette.muted, fontWeight: '600', fontSize: 13 },
  analyticsTextActive: { color: palette.ink },
  analyticsTotal: { backgroundColor: palette.mint, borderRadius: 18, padding: 18, marginBottom: 22 },
  analyticsPanel: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 15 },
  analyticsRow: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F0F3F0' },
  analyticsRowTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 },
  analyticsValue: { color: palette.ink, fontSize: 13, fontWeight: '700' },
  track: { height: 8, borderRadius: 4, backgroundColor: '#EFF2EF', overflow: 'hidden' },
  fill: { height: 8, borderRadius: 4 },
  emptyState: { backgroundColor: 'white', borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 24, alignItems: 'center' },
  emptyTitle: { color: palette.ink, fontSize: 15, fontWeight: '700' },
});
